import './globals.css'
import {Inter} from 'next/font/google'
import {ThemeManger} from "@/components/ThemeManger";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'sonarview',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {


    return (
        <html lang="de">
        <ThemeManger>
            <body className={inter.className}>
            {children}
            </body>
        </ThemeManger>
        </html>
    )
}