import './globals.css'
import {Inter} from 'next/font/google'

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {


    const routes = [
        {name: 'Dashboard', path: '/dashboard'},
        {name: 'Jobs', path: '/jobs'},
        // Add more routes as needed
    ];

    return (
        <html lang="de">
        <body className={inter.className}>

                {children}
        </body>
        </html>
    )
}