import './globals.css'
import {Inter} from 'next/font/google'
import {ThemeManger} from "@/components/ThemeManger";
import {ClerkProvider} from "@clerk/nextjs";
import Link from "next/link";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'sonarview',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {


    return (
        <ClerkProvider>
            <html lang="de">
            <body className={inter.className}>
            <ThemeManger>
                    {children}
            </ThemeManger>
            </body>
            </html>
        </ClerkProvider>
    )
}