export const STONE_HEIGHT = 6.5;
export const HOSE_DIAMETER = 3;
export const AVERAGE_WATER_USAGE_PER_MINUTE = 0.79190125;
export const AVERAGE_WATER_FILL_PER_MINUTE = 0.3000564;
export const RADIUS = 100;
export const MIN_WATER_HEIGHT = 2 + HOSE_DIAMETER + STONE_HEIGHT;
export const MAX_WATER_HEIGHT = 63.13;
export const HEIGHT_ABOVE_GROUND = 243.67;